# Generated by Django 5.1.2 on 2024-11-14 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25, unique=True)),
                ('uid_todo', models.CharField(blank=True, max_length=25, null=True)),
                ('link_image_todo', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_model', to='api.todomodel')),
            ],
        ),
    ]
